### ISSUE TITLE
Better store modules management and structure

### ISSUE THREAD

**Issue by vince19972** [tendermint/vue#23]
### Description 

The modules in `vuex` store is very important for this library because - 1) The `actions` are the public APIs for developers, and 2) We want to make the code easy to understand for developers customizing the components on their own. To achieve these goals, following improvements can be made:

### Tasks
- [ ] Have consensus on the structure of vuex modules
- [x] Test gRPC
- [x] Slice the `cosmos.js` module into individual modules responsible for different category of tasks
- [x] Flatten the namespaces of the modules to make the API cleaner

**Comment by vince19972** [comment]
Hey @fadeev , do you have any suggestions for organizing `bank` and `module` modules in `ui/develop` branch?

For `bank` module, we can either extract the part related to account matters into a `account` module, or keeping them together with a better name.

About `module` module, my intention was to keep everything related to customized types here; does this make sense? If it does, I'm sure a better naming for this module is required too.

Or if there's any better ways to organize the modules, let me know!

**Comment by fadeev** [comment]
Ideally, Vuex store API and structure should resemble the blockchain's API.

**Comment by vince19972** [comment]
> Ideally, Vuex store API and structure should resemble the blockchain's API.

You mean like Cosmos and Tendermint RPC REST endpoints? If so, would modules with namespaces make more sense? For example, `cosmos/txs/{hash}`.

**Comment by fadeev** [comment]
I was thinking more gRPC. Not a fan of `v1beta1`, and we need first to build gRPC for JS to actually see the API.

**Comment by vince19972** [comment]
I see. Hmmm I guess it's true that `v1beta1` is not very friendly for devs like me to use, but following the pattern of which should be fine for our purpose here?

**Comment by fadeev** [comment]
@vince19972 to figure this out I suggest we try using gRPC from JS even before CosmJS, for example by decoding the data from WebSockets.

**Comment by vince19972** [comment]
Mapping `vuex` store modules's data structure with `proto` files is a bigger scale task to work on. We can create another issue to discuss the topic.
