### ISSUE TITLE
[gRPC] Sync up with latest GetTx rpc service

### ISSUE THREAD

**Issue by vince19972** [tendermint/vue#34]
### Description

SDK just integrated [TxResponse](https://github.com/cosmos/cosmos-sdk/blob/master/proto/cosmos/tx/v1beta1/service.proto#L76) into the `GetTxResponse` from gRPC gateway 🎉 . We should abandon the temporary approach of combining two endpoints (#31) whenever we could.

### Todo
- [ ] Wait for SDK's release with this update
- [ ] Wait for Starport to upgrade SDK version
- [ ] Revise tx fetching code

**Comment by vince19972** [comment]
@fadeev @ilgooz  👆

**Comment by ilgooz** [comment]
tracked by https://github.com/tendermint/starport/pull/412.

**Comment by vince19972** [comment]
@ilgooz Yes that's no problem at all!

**Comment by fadeev** [comment]
Not relevant anymore.
